#+TITLE: The ECM Application and User Interface

This portion surrounds what the end-user calls ECM. It's the front
end, and the reason things in the backend exist at all.

It starts and ends here.

* The dynamic web server ensemble

Gerbil has a way to make an [[file:~/me/src/ecm/roam/20240216155826-ensemble.org:::ID: 298E9908-6F4F-495E-9D56-534C41ABCBE6][Ensemble]] web server pool that dynamically
runs Gerbil files in a structured way.

There is also a new [[file:~/me/src/ecm/roam/20240603144956-httpd.org:::ID: B4252815-C73B-4F68-9A77-DB6FF5CA0F13][approach to httpd]] and ensembly that we'll try out
here.

Most of the details are taken care of [[file:/srv/ecm/cloud/httpd/README.org][in the cloud]] so we'll look at
the UI details mostly.

* The WWW user Init!

  Every time a user starts the application up there is an =init.ss=
  file that initializes
  
#+begin_src scheme :tangle www/init.ss

  ;; What I thought should be here is upstream in the cloud

#+end_src

* The runtime meta logic

 1) The _only_ entry point is the [[file:/srv/ecm/app/www/index.html::<!DOCTYPE html>][index.html]] It does some JS and css
    loading but is essentially a blank canvas that we use to start a
    sketch. The ~<div id="EcmSPA" data-uri="init.html"> ... </div>~
    part is the sketch.
 
 2) That loads the SPA framework AKA paintbrushes. [[file:/srv/ecm/app/www/spa/README.org][Here]] are the
    details.

 3) When that is loaded, and the document is as well, we then [[file:/srv/ecm/app/www/init.html::<div
     id="ecmBody">][init.html]]'ize. This is where we load the paint essentially.


 4) "Finally" the [[file:/srv/ecm/app/www/main.html::<div id="ecmMain">][main.html]] is loaded and the painting starts.
 




* The Database




* The =SPA= files

There's a repository and "package" for the foundations of a =Single
Page Application= that acts like a multipage one [[https://github.com/Aufin/ecm-spa][here.]]

We want to incorporate it but also keep it free for use in other projects.

This is where a subtree comes in.

 1) Add the remote
    
    #+begin_src sh
      git remote add ecm-spa git@github.com:Aufin/ecm-spa.git
    #+end_src

 2)  Add the subtree
    #+begin_src sh
      git subtree add --prefix app/www/spa ecm-spa main
    #+end_src

    

 






