#+TITLE: The ECM Application and User Interface

This portion surrounds what the end-user calls ECM. It's the front
end, and the reason things in the backend exist at all.

It starts and ends here.

* The dynamic web server ensemble

Gerbil has a way to make an [[file:~/me/src/ecm/roam/20240216155826-ensemble.org:::ID: 298E9908-6F4F-495E-9D56-534C41ABCBE6][Ensemble]] web server pool that dynamically
runs Gerbil files in a structured way.

There is also a new [[file:~/me/src/ecm/roam/20240603144956-httpd.org:::ID: B4252815-C73B-4F68-9A77-DB6FF5CA0F13][approach to httpd]] and ensembly that we'll try out
here.

Most of the details are taken care of [[file:/srv/ecm/cloud/httpd/README.org][in the cloud]] so we'll look at
the UI details mostly.


* The =SPA= files

There's a repository and "package" for the foundations of a =Single
Page Application= that acts like a multipage one [[https://github.com/Aufin/ecm-spa][here.]]

We want to incorporate it but also keep it free for use in other projects.

This is where a subtree comes in.

** Subtree and Subfolder

I only want the =./spa/= folder as a part of the subtree.

This is doable!

 1) Add the =remote=

    #+begin_src sh
      git remote add ecm-spa git@github.com:Aufin/ecm-spa.git
    #+end_src

 2) Checkout =remote main/master= as a branch

    #+begin_src sh
      git fetch ecm-spa ; git checkout -b ecm-spa-main ecm-spa/main
    #+end_src

 3) Split the =remote spa/ subtree= into another branch: =ecm-spa-sub=

    #+begin_src sh
      git subtree split -P spa -b ecm-spa-sub --rejoin --annotate='(ecm-spa) '
    #+end_src

 4) Back to the =local main/master=

    #+begin_src sh
      git checkout main
    #+end_src

 5) Make the =local subtree= from that =subtree branch=

    #+begin_src sh
      git subtree add -P app/www/spa ecm-spa-sub
    #+end_src


 Now trying to propagate a change from this repo make to the master one.

   #+begin_src sh
     echo This is a subtree from a subtree > src/SPA/README.org
     git add src/spa/README.org
     git commit -m "Trying a subtree->subtree->main propa"
   #+end_src

   1) Push the subtree back to the other split subtree

      #+begin_src sh
	git subtree push -P src/spa . ecm-spa-sub
      #+end_src

   2) Checkout the main and pull!

      #+begin_src sh
	git branch ecm-spa-main -u ecm-spa/main
	git checkout ecm-spa-main
	git subtree pull -P spa/ . ecm-spa-sub --squash
      #+end_src

   3) Push it back upstream

      #+begin_src sh
	git push ecm-spa HEAD:main
      #+end_src

* Managers and Executives: The "Admin" portion







